/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.JFrame;

 
/**
 *
 * @author DELL
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_property = new javax.swing.JLabel();
        jLabel_propertyType = new javax.swing.JLabel();
        jLabel_propertyImages = new javax.swing.JLabel();
        jLabel_propertyOwner = new javax.swing.JLabel();
        jLabel_propertyClient = new javax.swing.JLabel();
        jLabel_sale = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/office-building (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        jLabel2.setText("REALTORS");

        jLabel3.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        jLabel3.setText("COLOMBO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel_property.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_property.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel_property.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_property.setText("  Property");
        jLabel_property.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel_property.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_property.setOpaque(true);
        jLabel_property.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_propertyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_propertyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_propertyMouseExited(evt);
            }
        });

        jLabel_propertyType.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_propertyType.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel_propertyType.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_propertyType.setText("  Property-Type");
        jLabel_propertyType.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel_propertyType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_propertyType.setOpaque(true);
        jLabel_propertyType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_propertyTypeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_propertyTypeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_propertyTypeMouseExited(evt);
            }
        });

        jLabel_propertyImages.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_propertyImages.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel_propertyImages.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_propertyImages.setText("  Property-Images");
        jLabel_propertyImages.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel_propertyImages.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_propertyImages.setOpaque(true);
        jLabel_propertyImages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_propertyImagesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_propertyImagesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_propertyImagesMouseExited(evt);
            }
        });

        jLabel_propertyOwner.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_propertyOwner.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel_propertyOwner.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_propertyOwner.setText("  Owner");
        jLabel_propertyOwner.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel_propertyOwner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_propertyOwner.setOpaque(true);
        jLabel_propertyOwner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_propertyOwnerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_propertyOwnerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_propertyOwnerMouseExited(evt);
            }
        });

        jLabel_propertyClient.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_propertyClient.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel_propertyClient.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_propertyClient.setText("  Client");
        jLabel_propertyClient.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel_propertyClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_propertyClient.setOpaque(true);
        jLabel_propertyClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_propertyClientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_propertyClientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_propertyClientMouseExited(evt);
            }
        });

        jLabel_sale.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_sale.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel_sale.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_sale.setText("  Sale");
        jLabel_sale.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel_sale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_sale.setOpaque(true);
        jLabel_sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_saleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_saleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_saleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_property, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_propertyType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_propertyImages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_propertyOwner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_propertyClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_sale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_property, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_propertyType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_propertyImages, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_propertyOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_propertyClient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_sale, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 211, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 764, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_propertyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyMouseEntered
        jLabel_property.setBackground(Color.white);
        jLabel_property.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jLabel_propertyMouseEntered

    private void jLabel_propertyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyMouseExited
        jLabel_property.setBackground(new Color(153,153,153));
        jLabel_property.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_propertyMouseExited

    private void jLabel_propertyTypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyTypeMouseEntered
        jLabel_propertyType.setBackground(Color.white);
        jLabel_propertyType.setForeground(new Color(153,153,153));    }//GEN-LAST:event_jLabel_propertyTypeMouseEntered

    private void jLabel_propertyTypeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyTypeMouseExited
        jLabel_propertyType.setBackground(new Color(153,153,153));
        jLabel_propertyType.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_propertyTypeMouseExited

    private void jLabel_propertyImagesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyImagesMouseEntered
        jLabel_propertyImages.setBackground(Color.white);
        jLabel_propertyImages.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jLabel_propertyImagesMouseEntered

    private void jLabel_propertyImagesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyImagesMouseExited
        jLabel_propertyImages.setBackground(new Color(153,153,153));
        jLabel_propertyImages.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_propertyImagesMouseExited

    private void jLabel_propertyOwnerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyOwnerMouseEntered
        jLabel_propertyOwner.setBackground(Color.white);
        jLabel_propertyOwner.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jLabel_propertyOwnerMouseEntered

    private void jLabel_propertyOwnerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyOwnerMouseExited
        jLabel_propertyOwner.setBackground(new Color(153,153,153));
        jLabel_propertyOwner.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_propertyOwnerMouseExited

    private void jLabel_propertyClientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyClientMouseEntered
        jLabel_propertyClient.setBackground(Color.white);
        jLabel_propertyClient.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jLabel_propertyClientMouseEntered

    private void jLabel_propertyClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyClientMouseExited
        jLabel_propertyClient.setBackground(new Color(153,153,153));
        jLabel_propertyClient.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_propertyClientMouseExited

    private void jLabel_propertyTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyTypeMouseClicked
        Property_Type typeform =new Property_Type();
        typeform.setVisible(true);
        typeform.pack();
        typeform.setLocationRelativeTo(null);
        typeform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jLabel_propertyTypeMouseClicked

    private void jLabel_propertyOwnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyOwnerMouseClicked
        Owner ownerform =new Owner();
        ownerform.setVisible(true);
        ownerform.pack();
        ownerform.setLocationRelativeTo(null);
        ownerform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_propertyOwnerMouseClicked

    private void jLabel_propertyClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyClientMouseClicked
         Client clientform =new Client();
        clientform.setVisible(true);
        clientform.pack();
        clientform.setLocationRelativeTo(null);
        clientform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_propertyClientMouseClicked

    private void jLabel_propertyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyMouseClicked
        Property propertyform =new Property();
        propertyform.setVisible(true);
        propertyform.pack();
        propertyform.setLocationRelativeTo(null);
        propertyform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_propertyMouseClicked

    private void jLabel_propertyImagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyImagesMouseClicked
        Property_image propertyImagesform =new Property_image();
        propertyImagesform.setVisible(true);
        propertyImagesform.pack();
        propertyImagesform.setLocationRelativeTo(null);
        propertyImagesform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_propertyImagesMouseClicked

    private void jLabel_saleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_saleMouseClicked
        Sale saleform =new Sale();
        saleform.setVisible(true);
        saleform.pack();
        saleform.setLocationRelativeTo(null);
        saleform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_saleMouseClicked

    private void jLabel_saleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_saleMouseEntered
        jLabel_sale.setBackground(Color.white);
        jLabel_sale.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jLabel_saleMouseEntered

    private void jLabel_saleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_saleMouseExited
      jLabel_sale.setBackground(new Color(153,153,153));
        jLabel_sale.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_saleMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_property;
    private javax.swing.JLabel jLabel_propertyClient;
    private javax.swing.JLabel jLabel_propertyImages;
    private javax.swing.JLabel jLabel_propertyOwner;
    private javax.swing.JLabel jLabel_propertyType;
    private javax.swing.JLabel jLabel_sale;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
