/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.p_property;
import Controller.p_type;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.Box;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Property_image extends javax.swing.JFrame {

        p_type type=new p_type();
        HashMap<String, Integer> map = type.getTypesMap();
        String property_image_path="";
        int propertyId;
        
        
    public Property_image() {
        initComponents();
        
        bindcombo();
        
        fillJtableWithPropertiesData();
        
        jTable_properties.setRowHeight(40);
        
        jTable_properties.setSelectionBackground(new Color(27,150,77));
        
        jTable_properties.getColumnModel().getColumn(0).setPreferredWidth(25);
        
        jTable_properties.getColumnModel().getColumn(1).setPreferredWidth(250);
        
    }
    
    
      public void bindcombo()
    {
         
        
        for (String s : map.keySet())
        {
            jComboBox_type.addItem(s);
        }
        
    }
      
      
      
     public void fillJtableWithPropertiesData()
    {
        p_property property = new p_property();
        ArrayList<p_property> PropertyList=property.propertiesList();
      
        String[] colNames={"id","address"};
        
        
        Object [][] rows = new Object[PropertyList.size()][2];
        
        for(int i=0;i<PropertyList.size();i++)
        {
            rows[i][0]=PropertyList.get(i).getId();
            rows[i][1]=PropertyList.get(i).getAddress();
        }
        
        DefaultTableModel model = new DefaultTableModel (rows,colNames);
        jTable_properties.setModel(model);
       
    }
    
      
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_show_image = new javax.swing.JButton();
        btn_delete_image = new javax.swing.JButton();
        jComboBox_type = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_properties = new javax.swing.JTable();
        btn_browse_img = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel_image = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btn_add_image = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel_Title.setBackground(new java.awt.Color(255, 51, 51));
        jPanel_Title.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(125, 125, 125)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Property - Images");

        javax.swing.GroupLayout jPanel_TitleLayout = new javax.swing.GroupLayout(jPanel_Title);
        jPanel_Title.setLayout(jPanel_TitleLayout);
        jPanel_TitleLayout.setHorizontalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitleLayout.createSequentialGroup()
                .addGap(515, 515, 515)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_TitleLayout.setVerticalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitleLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Select Type :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Select Image :");

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));

        btn_show_image.setBackground(new java.awt.Color(0, 153, 255));
        btn_show_image.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_show_image.setForeground(new java.awt.Color(255, 255, 255));
        btn_show_image.setText("Show This Property Images");
        btn_show_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_show_imageActionPerformed(evt);
            }
        });

        btn_delete_image.setBackground(new java.awt.Color(255, 51, 51));
        btn_delete_image.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_delete_image.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete_image.setText("Delete");
        btn_delete_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_imageActionPerformed(evt);
            }
        });

        jComboBox_type.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jComboBox_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_typeActionPerformed(evt);
            }
        });

        jTable_properties.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable_properties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_properties.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_propertiesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_properties);

        btn_browse_img.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_browse_img.setText("Browse");
        btn_browse_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browse_imgActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 0, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setOpaque(true);

        jLabel_image.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_image.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel_image.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_image.setText("                   ");
        jLabel_image.setOpaque(true);

        jList1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        btn_add_image.setBackground(new java.awt.Color(0, 153, 0));
        btn_add_image.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_add_image.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_image.setText("Add");
        btn_add_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_imageActionPerformed(evt);
            }
        });

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("* This table contains the properties ID and Address");

        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("* Select an item from the list to display or browse an image from your computer.");

        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("* This list contains the images ID of the");

        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("selected property.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jComboBox_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addComponent(btn_show_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(btn_delete_image, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(429, 429, 429)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(btn_browse_img))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_add_image, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_image, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_browse_img)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_delete_image, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_show_image, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_add_image, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_show_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_show_imageActionPerformed

        try
        {
            
         int rowIndex = jTable_properties.getSelectedRow();
         int id = Integer.valueOf(jTable_properties.getValueAt(rowIndex, 0).toString());
            
            
         
         
         if(jList1.getModel().getSize() > 0)
         {
            Property_image_slider imageSliderform =new Property_image_slider(id);
            imageSliderform.setVisible(true);
            imageSliderform.pack();
            imageSliderform.setLocationRelativeTo(null);
            imageSliderform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         }
         else
         {
             JOptionPane.showMessageDialog(null, "THSI PROPERTY DOESN'T HAVE ANY IMAGE TO SHOW"," No Images Found",2);
         }
         
         
         
        
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "SELECT PROPERTY FIRST","Prperty Not Selected",2);
        }
        
        

    }//GEN-LAST:event_btn_show_imageActionPerformed

    private void btn_delete_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_imageActionPerformed
       
        
       try{
            String selectedListItem = String.valueOf(jList1.getSelectedValue());
        Integer imageId = Integer.valueOf(selectedListItem);
        
        int yes_or_no= JOptionPane.showConfirmDialog(null, "DO YOU REALLY WANT TO DELETE THIS IMAGE ?","DELETE IMAGE",JOptionPane.YES_NO_OPTION);
        
         if(yes_or_no==JOptionPane.YES_OPTION)
                {
                    if(new p_property().removePropertyImage(imageId))
                    {

                        JOptionPane.showMessageDialog(null,"PROPERTY IMAGE DELETED","DELETE IMAGE",1);
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"OPERATION FAILED","DELETE IMAGE",2);
        }
        
                }
           
       }
       catch(Exception ex)
               {
                    JOptionPane.showMessageDialog(null,"NO IMAGE SELECTED","DELETE IMAGE",2);
               }
        
        
    }//GEN-LAST:event_btn_delete_imageActionPerformed

    
    public ImageIcon resizeImage (String path,byte[] byteImage)
    {
        
        ImageIcon pic;
        if(byteImage != null) pic=new ImageIcon(byteImage);
        else pic =new ImageIcon(path);
        
        Image img = pic.getImage().getScaledInstance(jLabel_image.getWidth(), jLabel_image.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img);
        return image;
    }
    
    
    private void btn_browse_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browse_imgActionPerformed
       
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("SELECT THE PROPERTY IMAGE");
        fileChooser.setCurrentDirectory(new File("c:\\images"));
        
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter ("Images",".jpg",".png",".jpeg");
        fileChooser.addChoosableFileFilter(fileFilter);
        
        int fileState = fileChooser.showSaveDialog(null);
        
        if(fileState==JFileChooser.APPROVE_OPTION)
        {
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            jLabel_image.setIcon(resizeImage(path,null) );
            property_image_path=path;
        }
        
        
        
        
        
    }//GEN-LAST:event_btn_browse_imgActionPerformed

    private void btn_add_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_imageActionPerformed
        p_property property = new p_property();
        
        if(propertyId != 0)
        {
            if(property.addImage(propertyId, property_image_path))
            {
            JOptionPane.showMessageDialog(null, "IMAGE ADDED TO THIS PROPERTY","Add Image",1);
            }
            else
            {
            JOptionPane.showMessageDialog(null, "IMAGE NOT ADDED TO THIS PROPERTY","Add Image",2);
            }
        }else
        {
            JOptionPane.showMessageDialog(null, "SELECT PROPERTY FIRST","Prperty Not Selected",2);
        }
        
    }//GEN-LAST:event_btn_add_imageActionPerformed

    private void jComboBox_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_typeActionPerformed
       
        int typeid = map.get(jComboBox_type.getSelectedItem().toString());
        p_property property = new p_property();
        ArrayList<p_property> PropertyList=property.propertiesListByType(typeid);
      
        String[] colNames={"id","address"};
        
        
        Object [][] rows = new Object[PropertyList.size()][2];
        
        for(int i=0;i<PropertyList.size();i++)
        {
            rows[i][0]=PropertyList.get(i).getId();
            rows[i][1]=PropertyList.get(i).getAddress();
        }
        
        DefaultTableModel model = new DefaultTableModel (rows,colNames);
        jTable_properties.setModel(model);
        
        
    }//GEN-LAST:event_jComboBox_typeActionPerformed

    private void jTable_propertiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_propertiesMouseClicked
        int rowIndex = jTable_properties.getSelectedRow();
        propertyId = Integer.valueOf(jTable_properties.getValueAt(rowIndex,0).toString());
        
        
        
        fillTypeList();
    }//GEN-LAST:event_jTable_propertiesMouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
       
        try
        {
            String selectedListItem = String.valueOf(jList1.getSelectedValue());
        Integer imageId = Integer.valueOf(selectedListItem);
        byte[] image = new p_property().getImageById(imageId);
        jLabel_image.setIcon(resizeImage("",image));
        }
        catch(Exception ex)
        {
            
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jList1MouseClicked

    
    public void fillTypeList()
    {
         
        
        HashMap<byte[],Integer> imagesListMap =new p_property().propertyImageList(propertyId);
        
        DefaultListModel listModel = new DefaultListModel ();
        
        int i=0;
        
        for(Integer id:imagesListMap.values())
        {
            listModel.add(i,id);
            i++;
        }
        jList1.setModel(listModel);
        
    }
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Property_image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Property_image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Property_image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Property_image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Property_image().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_image;
    private javax.swing.JButton btn_browse_img;
    private javax.swing.JButton btn_delete_image;
    private javax.swing.JButton btn_show_image;
    private javax.swing.JComboBox<String> jComboBox_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_properties;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
}
