/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Controller.p_type;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
//import Model.*;

/**
 *
 * @author DELL
 */
public class Property_Type extends javax.swing.JFrame {

    /**
     * Creates new form Property_Type
     */
    public Property_Type() {
        
        initComponents();
        
        fillTypeList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_description = new javax.swing.JTextArea();
        btn_add_type = new javax.swing.JButton();
        btn_edit_type = new javax.swing.JButton();
        btn_delete_type = new javax.swing.JButton();
        btn_refresh_type = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_type = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel_Title.setBackground(new java.awt.Color(153, 153, 153));
        jPanel_Title.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(125, 125, 125)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Property - Type");

        javax.swing.GroupLayout jPanel_TitleLayout = new javax.swing.GroupLayout(jPanel_Title);
        jPanel_Title.setLayout(jPanel_TitleLayout);
        jPanel_TitleLayout.setHorizontalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitleLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_TitleLayout.setVerticalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitleLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Description");

        txt_id.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        txt_name.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        txt_description.setColumns(20);
        txt_description.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txt_description.setRows(5);
        jScrollPane1.setViewportView(txt_description);

        btn_add_type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_add_type.setText("Add");
        btn_add_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_typeActionPerformed(evt);
            }
        });

        btn_edit_type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_edit_type.setText("Edit");
        btn_edit_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_typeActionPerformed(evt);
            }
        });

        btn_delete_type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_delete_type.setText("Delete");
        btn_delete_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_typeActionPerformed(evt);
            }
        });

        btn_refresh_type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_refresh_type.setText("Refresh");
        btn_refresh_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refresh_typeActionPerformed(evt);
            }
        });

        list_type.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        list_type.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_typeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(list_type);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btn_add_type, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addGap(72, 72, 72)
                        .addComponent(btn_edit_type, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btn_delete_type, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btn_refresh_type, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(txt_id))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(32, 32, 32)
                                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane3)))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_type, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit_type, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete_type, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_refresh_type, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void btn_add_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_typeActionPerformed
      
        //add new type
        
       String name=txt_name.getText();
       String description = txt_description.getText();
       
        p_type type =new p_type(0,name,description);
        
        if(!name.trim().equals(""))// if the type name is not empty
        {
            if(type.execTypeQuery("add",type))
        {
            JOptionPane.showMessageDialog(null,"NEW TYPE ADDED","ADD TYPE",1);
            fillTypeList();
            txt_description.setText("");
            txt_id.setText("");
            txt_name.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"OPERATION FAILED","ADD TYPE",2);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "ENTER TYPE NAME","EMPTY NAME",2);
        }
        
        
        
        
       
    }//GEN-LAST:event_btn_add_typeActionPerformed

    private void btn_refresh_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refresh_typeActionPerformed
       
        
        fillTypeList();
    }//GEN-LAST:event_btn_refresh_typeActionPerformed

    private void btn_edit_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_typeActionPerformed

         //edit type
        Integer id =Integer.valueOf(txt_id.getText()); 
       String name=txt_name.getText();
       String description = txt_description.getText();
       
        p_type type =new p_type(id,name,description);
        
        if(!name.trim().equals(""))// if the type name is not empty
        {
            if(type.execTypeQuery("edit",type))
        {
            JOptionPane.showMessageDialog(null,"TYPE UPDATED","EDIT TYPE",1);
            fillTypeList();
            txt_description.setText("");
            txt_id.setText("");
            txt_name.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"OPERATION FAILED","EDIT TYPE",2);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "ENTER TYPE NAME","EMPTY NAME",2);
        }
        
        
        
    }//GEN-LAST:event_btn_edit_typeActionPerformed

    public void fillTypeList()
    {
        p_type type=new p_type();
        
        HashMap<String, Integer> map = type.getTypesMap();
        
        DefaultListModel listModel = new DefaultListModel ();
        
        int i=0;
        
        for(String typeName:map.keySet())
        {
            listModel.add(i,typeName);
            i++;
        }
        list_type.setModel(listModel);
        
    }
    
    
    
    private void btn_delete_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_typeActionPerformed
         //Delete type
         
         try
         {
             Integer id =Integer.valueOf(txt_id.getText()); 
      
       
        p_type type =new p_type(id,"","");
        
        if(!txt_id.getText().trim().equals(""))// if the type id is not empty
        {
            //Show confirmation message before deleting
            int yes_or_no= JOptionPane.showConfirmDialog(null, "DO YOU WANT TO DELETE THIS TYPE ?","DELETE TYPE",JOptionPane.YES_NO_OPTION);
            if(yes_or_no==JOptionPane.YES_OPTION)
            {
                if(type.execTypeQuery("delete",type))
        {
            JOptionPane.showMessageDialog(null,"TYPE DELETED","DELETE TYPE",1);
            fillTypeList();
            txt_description.setText("");
            txt_id.setText("");
            txt_name.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"OPERATION FAILED","DELETE TYPE",2);
        }
            }
            
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "ENTER TYPE NAME","EMPTY NAME",2);
        }
         }
         catch(Exception ex)
                 {
                   JOptionPane.showMessageDialog(null, ex.getMessage()+"ENTER VALID TYPE ID","INVALID ID",2);

                 }
    }//GEN-LAST:event_btn_delete_typeActionPerformed

    private void list_typeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_typeMouseClicked
        p_type type =new p_type();
        HashMap<String, Integer> map=type.getTypesMap();
        Integer typeId = map.get(list_type.getSelectedValue());
        type = type.getTypeById(typeId); 
        txt_id.setText(type.getId().toString());
        txt_name.setText(type.getName());
        txt_description.setText(type.getDescription());
    }//GEN-LAST:event_list_typeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Property_Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Property_Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Property_Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Property_Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Property_Type().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_type;
    private javax.swing.JButton btn_delete_type;
    private javax.swing.JButton btn_edit_type;
    private javax.swing.JButton btn_refresh_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> list_type;
    private javax.swing.JTextArea txt_description;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
